### ISSUE TITLE
Help : You may not have created the entire video

### ISSUE THREAD

**Issue by DGSGamer12** [ryan-schroeder/sonic-candle#3]
Issue Image : http://i.imgur.com/llZdLAb.jpg

**Comment by Dakkra** [comment]
Hey DSGamer12, 

What format/codec is your input audio file? Could you provide a video example of what leads up to this occurring? If you can, but don't want to share it publicly, send me an email at contact@dakkra.com and I will work with you to resolve the issue there.

Chris Soderquist (Dakkra)
http://dakkra.com
contact@dakkra.com

**Comment by DGSGamer12** [comment]
I don't need help anymore ,I'm just forgot to convert the file. Thanks for replying.
